# Evaluate PII Inference
dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1
  limit_dataset_size: 10000

attack_args:
  attack_name: perplexity_inference
  sampling_rate: 100
  seq_len: 128

eval_args:
  num_candidates: 50

model_args:
  architecture: google/gemma-2-2b
  pre_trained: True
  client_number: 6
  csv_path: gemma-echr-inference
  fl_model_path: authorize/gemma_echer
  special_token: FoHL9UFVcTbcy80F5KZd
  model_ckpt: /scratch/user/mohamed.shaaban/mohamed_shaaban_9_20251226_100127/local_models/outputs_fl_gemma # Edit this path to try your own model.


ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
  tag_n_batches: 10_000
